### ISSUE TITLE
Directory is not correct

### ISSUE THREAD

**Issue by jeffreyfu1** [dmanlfc/arcade1up#1]
Directory is not correct in /etc/rc.local script:
(sudo python /home/pi/arcade1up/shutdown.py) &

(sudo python /home/pi/arcade1up/volume.py) &

Should be

(sudo python /home/pi/arcade1up/Raspberry\ Pi/shutdown.py) &

(sudo python /home/pi/arcade1up/Raspberry\ Pi/volume.py &

**Comment by dmanlfc** [comment]
yeah sorry I created a another directory on github to separate the raspberry pi & latte panda scripts.
I hope it worked out for you.

**Comment by D-an-W** [comment]
As above, the paths are still not right but works great if edited.
